[package]
name = "bicdb-exec"
description = "执行算子：火山拉取、行式、扫描/回表内部批量"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bicdb-common = { path = "../common" }
bicdb-index = { path = "../index" }
bicdb-storage = { path = "../storage" }
bicdb-types = { path = "../types" }

[dev-dependencies]
bicdb-txn = { path = "../txn" }
bicdb-wal = { path = "../wal" }
bicdb-workspace = { path = "../workspace" }
