[package]
name = "bicdb-sql"
description = "Raw AST、Binder、逻辑/物理计划、执行器"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bicdb-access = { path = "../access" }
bicdb-catalog = { path = "../catalog" }
bicdb-common = { path = "../common" }
bicdb-exec = { path = "../exec" }
bicdb-index = { path = "../index" }
bicdb-storage = { path = "../storage" }
bicdb-txn = { path = "../txn" }
bicdb-types = { path = "../types" }
bicdb-wal = { path = "../wal" }
bicdb-workspace = { path = "../workspace" }

bicdb-graph = { path = "../graph" }
serde_json = { version = "1.0.151", features = ["arbitrary_precision"] }
